# Ironically the task runner is itself a dev dependency of the project.
# To install it run the following command:
#
# go install github.com/go-task/task/v3/cmd/task@latest

version: '3'

tasks:
  fmt:
    cmds:
      - goimports -local github.com/davidmdm,github.com/davidmdm/halloumi -w .
      - gofumpt -w .

  platter:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o main.wasm ./cmd/examples/platter

  helmchart:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o main.wasm ./cmd/examples/helmchart
