# Ironically the task runner is itself a dev dependency of the project.
# To install it run the following command:
#
# go install github.com/go-task/task/v3/cmd/task@latest

version: '3'

tasks:
  fmt:
    cmds:
      - goimports -local github.com/davidmdm,github.com/davidmdm/halloumi -w .
      - gofumpt -w .

  test:
    cmds:
      - go test -cover -p 1 -v ./...

  platter:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o platter.wasm ./cmd/examples/platter

  helmchart:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o helmchart.wasm ./cmd/examples/helmchart

  helmexpanded:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o helmexpanded.wasm ./cmd/examples/helmexpanded
