name: release wasm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
          cache: true

      - name: Build and Release Flights
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          go run ./cmd/internal/releaser -cmd yokecd
